### ISSUE TITLE
Error in check conversion to HDF5

### ISSUE THREAD

**Issue by vuillaut** [GammaLearn/GammaLearn#1]
```
Ckeck conversion
Extract random image data from hdf5 file :  test0.hdf5
Traceback (most recent call last):
  File "conversion.py", line 43, in <module>
    dic = cv.extract_random_image_data_from_hdf5(hdf5name)
  File "/gpfs/LAPP-DATA/cta/vuillaume/GammaLearn/converter_hdf5/converter_hdf5.py", line 344, in extract_random_image_data_from_hdf5
    shaPs = [attr for attr in f['showerSimu/psimu_files'].attrs if
  File "/gpfs/LAPP-DATA/cta/vuillaume/GammaLearn/converter_hdf5/converter_hdf5.py", line 345, in <listcomp>
    (shower_index >= f['showerSimu/psimu_files'].attrs[attr][0]) & (shower_index <= f['showerSimu/psimu_files'].attrs[attr][1])]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by mikael10j** [comment]
I found the bug. At the creation of the hdf5 file, a wrong end index for shower and event simulation data was added (missing "- 1"). Could please check the updated code ?
