### ISSUE TITLE
Error on conversion check

### ISSUE THREAD

**Issue by vuillaut** [GammaLearn/GammaLearn#2]
I updated the conversion and tried a new one and got an error
```
Traceback (most recent call last):
  File "../converter_hdf5/conversion.py", line 43, in <module>
    dic = cv.extract_random_image_data_from_hdf5(hdf5name)
  File "/gpfs/LAPP-DATA/cta/vuillaume/GammaLearn/converter_hdf5/converter_hdf5.py", line 342, in extract_random_image_data_from_hdf5
    shaPs = [attr for attr in f['showerSimu/psimu_files'].attrs if
  File "/gpfs/LAPP-DATA/cta/vuillaume/GammaLearn/converter_hdf5/converter_hdf5.py", line 343, in <listcomp>
    (shower_index >= f['showerSimu/psimu_files'].attrs[attr][0]) & (shower_index <= f['showerSimu/psimu_files'].attrs[attr][1])]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

However, launching the conversion again I did not get it.

**Comment by mikael10j** [comment]
As discussed, showerId are finally not unique. A new version taking into account the run number will be soon pushed.
